# Generated by Django 3.2 on 2023-09-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('booked_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_type', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LugaggePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=500)),
                ('bus_source', models.CharField(max_length=50)),
                ('departure_station', models.CharField(max_length=500)),
                ('bus_destination', models.CharField(max_length=50)),
                ('destination_station', models.CharField(max_length=500)),
                ('bus_departure_time', models.TimeField()),
                ('bus_arrival_time', models.TimeField()),
                ('bus_fare', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(max_length=500)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('rows', models.CharField(max_length=500)),
                ('seat_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('seat_label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_image', models.ImageField(default='images/None/Noimg.jpg', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED_NOT_PAID', 'BOOKED_NOT_PAID'), ('BOOKED_PAID', 'BOOKED_PAID')], default='BOOKED_NOT_PAID', max_length=500)),
                ('startdatetime_counting_deadline_for_it_to_be_marked_deleted', models.DateTimeField(blank=True, null=True)),
                ('mark_it_deleted', models.BooleanField(default=False)),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
                ('seats', models.ManyToManyField(to='bus.BookedSeat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BusAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.AddField(
            model_name='bookedseat',
            name='seat_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.busseat'),
        ),
    ]
