# Generated by Django 3.2 on 2023-09-26 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseatlayout',
            name='seat_type',
            field=models.CharField(choices=[('1 by 2', '1 by 2'), ('2 by 2', '2 by 2'), ('2 by 3', '2 by 3'), ('3 by 3', '3 by 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lugaggeprice',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo'),
        ),
    ]
