# Generated by Django 3.2 on 2023-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20230926_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustrip',
            name='bus_arrival_time',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='bus_departure_time',
            field=models.CharField(max_length=500),
        ),
    ]
