# Generated by Django 3.2 on 2023-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20230926_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustrip',
            name='destination_arrival_time',
            field=models.CharField(help_text='eg. 17:30, put format in 24 hours, muda wa basi kufika kituo cha mwisho cha safari', max_length=500),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='source_arrival_time',
            field=models.CharField(help_text='eg. 17:30, put format in 24 hours, muda wa basi kufika kituo cha kuanza safari', max_length=500),
        ),
    ]
