# Generated by Django 3.2 on 2023-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20230926_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='bookingId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
