# Generated by Django 3.2 on 2023-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_alter_busbooking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='bookingId',
            field=models.CharField(max_length=255),
        ),
    ]
