# Generated by Django 3.2 on 2023-09-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_alter_busbooking_bookingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustrip',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bustrip', to='bus.businfo'),
        ),
    ]
