# Generated by Django 3.2 on 2023-09-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_alter_bustrip_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='bustrip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bustrip'),
        ),
    ]
