# Generated by Django 3.2 on 2023-09-30 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
        ('bus', '0011_busbooking_bustrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedseat',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.customuser'),
        ),
    ]
