# Generated by Django 3.2 on 2023-10-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0014_rename_startdatetime_counting_deadline_for_it_to_be_marked_deleted_busbooking_startdatetime_counting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busbooking',
            old_name='startdatetime_counting_deadline_for_it_to_be_deleted_if_not_paid',
            new_name='startdatetime_counting_deadline_for_it_to_be_deleted',
        ),
    ]
