# Generated by Django 3.2 on 2023-10-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0015_rename_startdatetime_counting_deadline_for_it_to_be_deleted_if_not_paid_busbooking_startdatetime_cou'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone1', models.CharField(max_length=500)),
                ('phone2', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='busbooking',
            old_name='startdatetime_counting_deadline_for_it_to_be_deleted',
            new_name='time_to_be_deleted_if_its_not_paid',
        ),
        migrations.RemoveField(
            model_name='bookedseat',
            name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='bookedseat',
            name='phone',
        ),
        migrations.AddField(
            model_name='busbooking',
            name='booker_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.bookerinfo'),
        ),
    ]
