# Generated by Django 3.2 on 2023-10-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0016_auto_20231019_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busseat',
            name='seat_number',
        ),
    ]
