# Generated by Django 3.2 on 2023-10-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0017_remove_busseat_seat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_timeout_to_pay_for_each_cycle', models.IntegerField(default=15, help_text='In minutes')),
            ],
        ),
    ]
