# Generated by Django 3.2 on 2023-12-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0018_othermetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='businfo',
            name='color',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.buscolor'),
        ),
    ]
