# Generated by Django 3.2 on 2023-12-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0019_auto_20231219_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businfo',
            name='color',
        ),
        migrations.AddField(
            model_name='businfo',
            name='primary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus.buscolor'),
        ),
    ]
